// Copyright 2025-2026 Yi-Ping Pan (Cloudlet)

#include <string>
#include <vector>

#include "stratum/cache_sim.hpp"
#include "stratum/simulation.hpp"

using namespace stratum;

// ============================================================================
// CACHE CONFIGURATION (Generated by Racket/User)
// ============================================================================
int main() {
  // Define Cache Types
  using MemType = MainMemory<"MainMemory">;
  // <Name, Next, Sets, Ways, Block, Policy, Latency>
  using L3Type = Cache<"L3", MemType, 8192, 16, 64, LRUPolicy, 20>;
  using L2Type = Cache<"L2", L3Type, 512, 8, 64, LRUPolicy, 10>;
  using L1Type = Cache<"L1", L2Type, 64, 8, 64, LRUPolicy, 4>;

  // Define Hierarchy for Stats
  std::vector<std::string> hierarchy = {"L1", "L2", "L3", "MainMemory"};

  // Define Traces
  const std::string project_root = STRATUM_ROOT;
  std::vector<std::pair<std::string, std::string>> traces = {
      {"Sequential", project_root + "/test/data/sequential.txt"},
      {"Random", project_root + "/test/data/random.txt"},
      {"Temporal", project_root + "/test/data/temporal.txt"},
      {"Spatial", project_root + "/test/data/spatial.txt"},
      {"LargeLoop", project_root + "/test/data/largeloop.txt"},
      {"Gaussian", project_root + "/test/data/gaussian.txt"}};

  // Run Simulations
  for (const auto& t : traces) {
    RunTraceSimulation<L1Type>(t.first, t.second, hierarchy);
  }

  return 0;
}
